apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: podcast-converter
type: Opaque
data:
  access_key_id: <base64-encoded-access-key>
  secret_access_key: <base64-encoded-secret-key>